Algoritmo "CONVERTER DÓLAR"


Var
valoremReal, conversao, valorFinal: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite a quantidade que deseja converter:R$")
leia(valoremReal)
escreval("Digite o valor do dolar hoje : R$")
leia(valorFinal)
conversao<-valoremReal/valorFinal
escreval("Isso é a quantidade de Dolares :", Conversao:2:2)

Fimalgoritmo