Algoritmo "horas_trabalhadas (SUCESSO TOTAL)"

Var
valorhora, dias, salariototal, horas: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Informe a quantidade de dias trabalhadas: ")
  leia(dias)
  
  escreva("Informe a quantidade de horas trabalhadas por dia: ")
  leia(horas)

  escreval()
  
  valorhora <- 25
  salariototal <- dias * 25 * horas
  
  
 escreval("O salário total é: ", salariototal)
 escreval
 
Fimalgoritmo