Algoritmo "terreno"

Var
base, altura, area: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("**************** SUPER TERRENO CALCULATOR 3100 ****************")
escreval()
escreval()

escreva("Olá, informe a base do terreno: ")
leia(base)

escreva("Olá, informe a altura do terreno: ")
leia(altura)

area <- (base * altura)

escreva ("Esse terreno tem uma área de: ", area)


Fimalgoritmo